#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright 2013 Red Hat, Inc.
# Part of clufter project
# Licensed under GPLv2 (a copy included | http://gnu.org/licenses/gpl-2.0.txt)
"""The launcher"""
__author__ = "Jan Pokorný <jpokorny @at@ Red Hat .dot. com>"

from sys import argv, exit, path
from os.path import dirname, abspath
path.insert(0, reduce(lambda x, y: dirname(x), xrange(2), abspath(__file__)))

from clufter import main

if __name__ == '__main__':
    exit(main.run(argv[1:]))
