#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright 2014 Red Hat, Inc.
# Part of clufter project
# Licensed under GPLv2 (a copy included | http://gnu.org/licenses/gpl-2.0.txt)
"""Machinery entry point -- to be run from in-repo location"""
__author__ = "Jan Pokorný <jpokorny @at@ Red Hat .dot. com>"

import imp
imp.load_source('_bootstrap', 'tests/_bootstrap.py')
from clufter.main import run

if __name__ == '__main__':
    from sys import argv
    run(argv)
