#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright 2014 Red Hat, Inc.
# Part of clufter project
# Licensed under GPLv2+ (a copy included | http://gnu.org/licenses/gpl-2.0.txt)
"""Machinery entry point -- to be run from in-repo location"""
__author__ = "Jan Pokorný <jpokorny @at@ Red Hat .dot. com>"

from imp import load_source
from os.path import dirname, join, abspath
from sys import argv, exit

bootstrap = join(dirname(abspath(__file__)), 'tests', '_bootstrap.py')
__package__ = getattr(load_source('main_bootstrap', bootstrap), '__package__')
from .main import run

exit(run(argv))
