#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright 2014 Red Hat, Inc.
# Part of clufter project
# Licensed under GPLv2 (a copy included | http://gnu.org/licenses/gpl-2.0.txt)
"""The launcher"""
__author__ = "Jan Pokorný <jpokorny @at@ Red Hat .dot. com>"

from sys import argv, exit
from clufter import main

if __name__ == '__main__':
    exit(main.run(argv[1:]))
